### ISSUE TITLE
Add github actions

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fdp-cli#17]
Add github actions for:
-testing and building
-npm publish
-github release

**Comment by crtahlin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fair-Data-Protocol-61f37a061754030017d022ea/issues/fairDataSociety/fdp-cli/17?planning-poker) with ZenHub @IgorShadurin @nugaon
