### ISSUE TITLE
Cannot read properties on undefined - account create

### ISSUE THREAD

**Issue by nugaon** [fairDataSociety/fdp-cli#43]
When I'm executing `$ fdp-cli account create`
I get error message
```
No account name specified, defaulting to 'main'
ERROR Cannot read properties of undefined (reading 'main')`
```

**Comment by nugaon** [comment]
also trying out with the `$ fdp-cli  account register main`
```
No portable password specified with the '--portable-password' option
? Enter a password for the portable FDS account [hidden]
? Enter a password again for the portable FDS account [hidden]
ERROR Failed to register account: No accounts found. Create one with the command 'account create'
```
I think if it requires registered account before, then it should check first whether the given account name exists already before password inputs.

**Comment by IgorShadurin** [comment]
Most likely you have an old configuration file from a previous version. It is located in the user directory/.fdp-cli
After deleting the file, there should be no such error.
Created an issue to validate this file before use - https://github.com/fairDataSociety/fdp-cli/issues/44
