### ISSUE TITLE
Lacking of Blockchain environment config

### ISSUE THREAD

**Issue by nugaon** [fairDataSociety/fdp-cli#51]
`fdpStorage` field is initialized with the defaults for reaching out RPC server for blockchain connection and ENS.
There should be a set of environments (currently `Goerli` and `fdp-play`) in form of an enum flag that provides defaults for the granular configuration (also should be possible to set by flags, at least the RpcUrl) of the `ensOptions` of the FdpStorage instance.

**Comment by tfius** [comment]
lets merge this
