### ISSUE TITLE
gas price issue on registration

### ISSUE THREAD

**Issue by nugaon** [fairDataSociety/fdp-cli#55]
When executing `fdp-cli account register [accountName]`
The following error will be thrown:
`ERROR Failed to register account: insufficient funds for gas * price + value`

**Comment by IgorShadurin** [comment]
> When executing `fdp-cli account register [accountName]` The following error will be thrown: `ERROR Failed to register account: insufficient funds for gas * price + value`

On the account with which there is a registration of finances?

**Comment by nugaon** [comment]
yeah, my bad, it was an account that was not funded before
